#!/usr/bin/env python
"""Analyze NPY outputs generated by export_logit_lens.py.

Writes per-layer summary CSV and figures showing direction alignment and
watermark-vs-base top-logit changes.
"""

import argparse
import csv
import json
from pathlib import Path

import numpy as np


def parse_args():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("input_dir", help="Directory containing logit-lens NPY files")
    p.add_argument("--top-k", type=int, default=None,
                   help="Number of saved top-k ranks to inspect; default uses all")
    p.add_argument("--output-dir", default=None,
                   help="Output directory; default is the input directory")
    return p.parse_args()


def load_data(directory):
    directory = Path(directory)
    required = ("top_token_ids.npy", "top_logits.npy", "direction_cosine.npy", "token_ids.npy", "metadata.json")
    missing = [name for name in required if not (directory / name).is_file()]
    if missing:
        raise FileNotFoundError(f"Missing logit-lens files: {', '.join(missing)}")
    ids = np.load(directory / "top_token_ids.npy", allow_pickle=False)
    logits = np.load(directory / "top_logits.npy", allow_pickle=False)
    direction = np.load(directory / "direction_cosine.npy", allow_pickle=False)
    token_ids = np.load(directory / "token_ids.npy", allow_pickle=False)
    metadata = json.loads((directory / "metadata.json").read_text(encoding="utf-8"))
    if (ids.ndim != 4 or logits.shape != ids.shape or direction.shape != ids.shape[:3]
            or token_ids.shape != (ids.shape[2],)):
        raise ValueError(f"Unexpected shapes: top_ids={ids.shape}, top_logits={logits.shape}, direction={direction.shape}, token_ids={token_ids.shape}")
    if ids.shape[0] != 2:
        raise ValueError("Expected model axis of length 2: [model_a, model_b]")
    return directory, ids, logits, direction, token_ids, metadata


def analyze(ids, logits, direction, token_ids, metadata, top_k):
    model_a, model_b = 0, 1
    layers, tokens, saved_k = ids.shape[1:]
    k = saved_k if top_k is None else min(top_k, saved_k)
    rows = []
    for layer in range(layers):
        a_ids = ids[model_a, layer, :, :k]
        b_ids = ids[model_b, layer, :, :k]
        a_logits = logits[model_a, layer, :, :k]
        b_logits = logits[model_b, layer, :, :k]
        same_top1 = float(np.mean(a_ids[:, 0] == b_ids[:, 0]))
        overlap = np.mean(np.any(a_ids[:, :, None] == b_ids[:, None, :], axis=2), axis=1)
        delta = b_logits - a_logits
        rows.append({
            "layer": layer,
            "base_direction_cosine_mean": float(direction[model_a, layer].mean()),
            "k0_direction_cosine_mean": float(direction[model_b, layer].mean()),
            "direction_cosine_gap_k0_minus_base": float(direction[model_b, layer].mean() - direction[model_a, layer].mean()),
            "top1_token_agreement": same_top1,
            "top_k_token_overlap_mean": float(overlap.mean()),
            "top_k_logit_delta_mean": float(np.nanmean(delta)),
            "top_k_logit_delta_max": float(np.nanmax(delta)),
            "tokens": tokens,
        })
    return rows


def save_outputs(out_dir, rows, ids, logits, direction, token_ids, metadata):
    out_dir.mkdir(parents=True, exist_ok=True)
    csv_path = out_dir / "logit_lens_summary.csv"
    with csv_path.open("w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=list(rows[0]))
        writer.writeheader()
        writer.writerows(rows)
    np.savez_compressed(out_dir / "logit_lens_summary.npz",
                        layer=np.asarray([r["layer"] for r in rows]),
                        base_direction_cosine=np.asarray([r["base_direction_cosine_mean"] for r in rows]),
                        k0_direction_cosine=np.asarray([r["k0_direction_cosine_mean"] for r in rows]),
                        top1_token_agreement=np.asarray([r["top1_token_agreement"] for r in rows]),
                        top_k_token_overlap=np.asarray([r["top_k_token_overlap_mean"] for r in rows]),
                        top_k_logit_delta=np.asarray([r["top_k_logit_delta_mean"] for r in rows]))
    (out_dir / "analysis_metadata.json").write_text(json.dumps({
        "source_metadata": metadata,
        "definition": "Per-layer summary of top-k projected logit-lens outputs",
        "saved_arrays": {"top_token_ids": "[model, layer, token, rank]", "top_logits": "[model, layer, token, rank]"},
    }, ensure_ascii=False, indent=2), encoding="utf-8")

    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    layers = np.asarray([r["layer"] for r in rows])
    fig, axes = plt.subplots(1, 3, figsize=(17, 4.8))
    axes[0].plot(layers, [r["base_direction_cosine_mean"] for r in rows], label="base", marker="o")
    axes[0].plot(layers, [r["k0_direction_cosine_mean"] for r in rows], label="k0", marker="o")
    axes[0].set_title("Direction cosine to final layer")
    axes[0].set_ylabel("cosine")
    axes[0].legend()
    axes[1].plot(layers, [r["top1_token_agreement"] for r in rows], marker="o", color="#7c3aed")
    axes[1].set_title("Top-1 token agreement")
    axes[1].set_ylabel("fraction")
    axes[2].plot(layers, [r["top_k_token_overlap_mean"] for r in rows], marker="o", color="#059669", label="top-k overlap")
    axes[2].plot(layers, [r["top_k_logit_delta_mean"] for r in rows], marker="o", color="#dc2626", label="k0-base top-k logit delta")
    axes[2].set_title("Top-k changes")
    axes[2].legend(fontsize=8)
    for ax in axes:
        ax.set_xlabel("hidden-state layer (0 = embedding)")
        ax.grid(alpha=.25)
    fig.tight_layout()
    plot_path = out_dir / "logit_lens_analysis.png"
    fig.savefig(plot_path, dpi=170, bbox_inches="tight")
    plt.close(fig)
    return csv_path, plot_path


def main():
    args = parse_args()
    source, ids, logits, direction, token_ids, metadata = load_data(args.input_dir)
    rows = analyze(ids, logits, direction, token_ids, metadata, args.top_k)
    out = Path(args.output_dir) if args.output_dir else source
    csv_path, plot_path = save_outputs(out, rows, ids, logits, direction, token_ids, metadata)
    print(f"Saved summary table: {csv_path}")
    print(f"Saved analysis plot: {plot_path}")
    print("Layer | base direction | k0 direction | top1 agreement | top-k overlap")
    for row in rows:
        print(f"{row['layer']:5d} | {row['base_direction_cosine_mean']:.5f} | {row['k0_direction_cosine_mean']:.5f} | "
              f"{row['top1_token_agreement']:.5f} | {row['top_k_token_overlap_mean']:.5f}")


if __name__ == "__main__":
    main()
