#!/usr/bin/env python3
"""Extract per-layer causal hidden states labelled by KGW green/red membership.

Each row is the hidden state at position t (the representation used to predict
input token t+1). The label is whether input token t+1 belongs to the KGW
 green-list seeded by the prefix ending at input token t.

Example:
  python analysis/extract_kgw_probe_embeddings.py \
    --model pretrained/pythia-1.4b-sampling-watermark-distill-kgw-k0-gamma0.25-delta2 \
    --texts data/prompts.txt --output analysis/kgw_probe_k0_d2.pt --k 0 --delta 2
"""
import argparse
import json
import random
import sys
from pathlib import Path

import numpy as np
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))
from watermarks.kgw.watermark_processor import WatermarkDetector


def parse_args():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--model", required=True,
                   help="Llama-2/Pythia model ID or local checkpoint")
    p.add_argument("--texts", required=True, help="UTF-8 file, one text/prompt per line")
    p.add_argument("--output", required=True, help="Output .pt file")
    p.add_argument("--k", type=int, choices=(0, 1, 2), required=True)
    p.add_argument("--delta", type=int, choices=(1, 2), default=2)
    p.add_argument("--gamma", type=float, default=0.25)
    p.add_argument("--seeding-scheme", default=None)
    p.add_argument("--device", choices=("auto", "cpu", "cuda"), default="auto")
    p.add_argument("--trust-remote-code", action="store_true")
    p.add_argument("--load-in-8bit", action="store_true",
                   help="Use bitsandbytes 8-bit loading (useful for Llama-2-7B)")
    p.add_argument("--load-in-4bit", action="store_true",
                   help="Use bitsandbytes 4-bit loading (lowest VRAM; requires bitsandbytes)")
    p.add_argument("--batch-size", type=int, default=1,
                   help="Kept for CLI compatibility; generation is prompt-by-prompt")
    p.add_argument("--max-length", type=int, default=256,
                   help="Maximum prompt length before continuation generation")
    p.add_argument("--max-new-tokens", type=int, default=128,
                   help="Number of tokens generated by Pythia for each prompt")
    p.add_argument("--temperature", type=float, default=1.0)
    p.add_argument("--top-p", type=float, default=1.0)
    p.add_argument("--greedy", action="store_true",
                   help="Use greedy decoding instead of sampling")
    p.add_argument("--max-points", type=int, default=100000,
                   help="Maximum labelled positions; use 0 for unlimited")
    p.add_argument("--min-context", type=int, default=None,
                   help="Minimum prefix length; defaults to KGW context width")
    p.add_argument("--balance", action="store_true",
                   help="Keep equal numbers of green and red rows")
    p.add_argument("--seed", type=int, default=42)
    p.add_argument("--generations-output", default=None,
                   help="Optional JSONL file saving each prompt and generated continuation")
    p.add_argument("--input-generations", default=None,
                   help="Reuse an existing generations JSONL and skip model.generate")
    return p.parse_args()


def main():
    args = parse_args()
    random.seed(args.seed)
    np.random.seed(args.seed)
    device = ("cuda" if torch.cuda.is_available() else "cpu") if args.device == "auto" else args.device
    if device == "cuda" and not torch.cuda.is_available():
        raise RuntimeError("CUDA requested but unavailable")
    texts = [x.strip() for x in Path(args.texts).read_text(encoding="utf-8").splitlines() if x.strip()]
    if not texts:
        raise ValueError("--texts contains no non-empty lines")
    tokenizer = AutoTokenizer.from_pretrained(
        args.model, use_fast=True, trust_remote_code=args.trust_remote_code
    )
    if tokenizer.pad_token_id is None:
        tokenizer.pad_token = tokenizer.eos_token
    # Llama-2 has no pad token by default; left padding is not used, but an
    # explicit pad token avoids generation warnings and keeps attention masks valid.
    tokenizer.padding_side = "right"
    load_kwargs = {"trust_remote_code": args.trust_remote_code}
    if args.load_in_4bit or args.load_in_8bit:
        if device != "cuda":
            raise RuntimeError("--load-in-4bit/8bit requires --device cuda")
        load_kwargs["device_map"] = "auto"
        load_kwargs["quantization_config"] = BitsAndBytesConfig(
            load_in_4bit=args.load_in_4bit,
            load_in_8bit=args.load_in_8bit,
            bnb_4bit_compute_dtype=torch.float16,
            bnb_4bit_quant_type="nf4",
            bnb_4bit_use_double_quant=True,
        )
    else:
        load_kwargs["torch_dtype"] = torch.float16 if device == "cuda" else torch.float32
    model = AutoModelForCausalLM.from_pretrained(args.model, **load_kwargs)
    if not (args.load_in_4bit or args.load_in_8bit):
        model.to(device)
    model.eval()
    scheme = args.seeding_scheme or f"simple_{args.k}"
    detector = WatermarkDetector(
        vocab=list(tokenizer.get_vocab().values()), gamma=args.gamma,
        seeding_scheme=scheme, tokenizer=tokenizer,
        device=torch.device("cpu"), normalizers=[]
    )
    min_context = args.min_context or detector.context_width
    layers = None
    labels = []
    rows_by_layer = None
    processed = 0
    generation_records = []
    generation_path = Path(args.generations_output) if args.generations_output else None
    input_generation_path = Path(args.input_generations) if args.input_generations else None
    if input_generation_path:
        generation_records = [json.loads(line) for line in input_generation_path.read_text(encoding="utf-8").splitlines() if line.strip()]
        if not generation_records:
            raise ValueError(f"No records found in {input_generation_path}")
        prompts_to_process = generation_records
    else:
        prompts_to_process = [{"prompt_index": i, "prompt": p} for i, p in enumerate(texts)]
    with torch.inference_mode():
        for index, record in enumerate(prompts_to_process):
            prompt = record["prompt"]
            enc = tokenizer(prompt, return_tensors="pt", truncation=True,
                            max_length=args.max_length)
            prompt_ids = enc["input_ids"].to(device)
            prompt_mask = enc["attention_mask"].to(device)
            if input_generation_path:
                continuation_ids = tokenizer(record["continuation"], add_special_tokens=False,
                                             return_tensors="pt")["input_ids"].to(device)
                generated = torch.cat([prompt_ids, continuation_ids], dim=1)
            else:
                generated = model.generate(
                    input_ids=prompt_ids, attention_mask=prompt_mask,
                    max_new_tokens=args.max_new_tokens,
                    do_sample=not args.greedy,
                    temperature=max(args.temperature, 1e-5),
                    top_p=args.top_p,
                    pad_token_id=tokenizer.pad_token_id,
                )
            # Analyze the complete prompt+continuation sequence. Prompt positions are
            # retained as context, but only continuation-token labels are collected.
            prompt_len = int(prompt_mask[0].sum())
            ids = generated[0].detach().cpu()
            continuation = ids[prompt_len:]
            if not input_generation_path:
                generation_records.append({
                    "prompt_index": index,
                    "prompt": prompt,
                    "continuation": tokenizer.decode(continuation, skip_special_tokens=True),
                    "prompt_tokens": prompt_len,
                    "generated_tokens": int(len(continuation)),
                })
            out = model(input_ids=generated, output_hidden_states=True, return_dict=True)
            if layers is None:
                layers = len(out.hidden_states)
                rows_by_layer = [[] for _ in range(layers)]
            # hidden state at t predicts token t+1. Only score generated tokens.
            for t in range(max(min_context - 1, prompt_len - 1), len(ids) - 1):
                prefix = ids[:t + 1]
                target = int(ids[t + 1])
                green = detector._get_greenlist_ids(prefix)
                label = int(target in green.tolist())
                labels.append(label)
                for li, hidden in enumerate(out.hidden_states):
                    rows_by_layer[li].append(hidden[0, t].detach().float().cpu())
                processed += 1
                if args.max_points and processed >= args.max_points:
                    break
            print(f"processed prompts {index + 1}/{len(texts)}; points={processed}")
            if args.max_points and processed >= args.max_points:
                break
    if generation_path and not input_generation_path:
        generation_path.parent.mkdir(parents=True, exist_ok=True)
        with generation_path.open("w", encoding="utf-8") as handle:
            for record in generation_records:
                handle.write(json.dumps(record, ensure_ascii=False) + "\n")
        print(f"saved generations: {generation_path}")
    elif input_generation_path:
        print(f"reused generations: {input_generation_path}")
    if not labels:
        raise RuntimeError("No labelled positions; increase --max-length or lower --min-context")
    labels_np = np.asarray(labels, dtype=np.int64)
    raw_count = int(len(labels_np))
    raw_green_count = int(labels_np.sum())
    if args.balance:
        rng = np.random.default_rng(args.seed)
        green = np.flatnonzero(labels_np == 1)
        red = np.flatnonzero(labels_np == 0)
        n = min(len(green), len(red))
        if n == 0:
            raise RuntimeError("Cannot balance: only one class was observed")
        keep = np.concatenate([rng.choice(green, n, replace=False), rng.choice(red, n, replace=False)])
        rng.shuffle(keep)
        labels_np = labels_np[keep]
        rows_by_layer = [[rows[i] for i in keep] for rows in rows_by_layer]
    payload = {
        "embeddings": [torch.stack(rows) for rows in rows_by_layer],
        "labels": torch.from_numpy(labels_np),
        "metadata": {
            "model": args.model, "k": args.k, "delta": args.delta,
            "gamma": args.gamma, "seeding_scheme": scheme,
            "context_width": detector.context_width, "balanced": args.balance,
            "max_new_tokens": args.max_new_tokens, "temperature": args.temperature,
            "top_p": args.top_p, "raw_count": raw_count,
            "raw_green_count": raw_green_count,
            "raw_green_fraction": (raw_green_count / raw_count if raw_count else None),
            "count": int(len(labels_np)),
            "green_count": int(labels_np.sum()),
            "green_fraction": float(labels_np.mean()),
            "layers": len(rows_by_layer), "generated_prompt_count": len(generation_records),
        },
    }
    output = Path(args.output)
    output.parent.mkdir(parents=True, exist_ok=True)
    torch.save(payload, output)
    print(json.dumps(payload["metadata"], indent=2))
    print(f"saved {output} (labels: green={int(labels_np.sum())}, red={int((labels_np == 0).sum())})")


if __name__ == "__main__":
    main()
